def test_quiz_fallback_503(client):
    # Setup
    client.post("/api/v1/auth/register", json={"email": "fb@test.com", "password": "pass", "role": "student"})
    token = client.post("/api/v1/auth/login", data={"username": "fb@test.com", "password": "pass"}).json()["access_token"]
    
    # Post targeted format simulating the exact mock "timeout" condition internally 
    mat_res = client.post("/api/v1/materials/", 
                          json={"title": "Error Gen", "source_url": "https://example.com/timeout.pdf", "file_format": "PDF"},
                          headers={"Authorization": f"Bearer {token}"})
    material_id = mat_res.json()["id"]

    gen_res = client.post("/api/v1/quizzes/generate", json={"material_id": material_id, "difficulty": "HARD"}, headers={"Authorization": f"Bearer {token}"})
    
    # Assert standard structured Failure cleanly generated bypassing 422 structurally
    assert gen_res.status_code == 503
    assert "timeout" in gen_res.json()["detail"].lower()
