version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: rakizz_user
      POSTGRES_PASSWORD: rakizz_password
      POSTGRES_DB: rakizz_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
